import 'package:get/get_navigation/src/root/internacionalization.dart';

class Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'google_text': 'Google',
      'facebook_text': 'Facebook',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'enter_code': 'Please enter the Following details.',
      'username': 'Username',
      'email': 'Email',
      'return_mail': 'Please enter email',
      'return_username': 'Please enter Username',
      'return_password': 'Please enter Password',
      'return_confirm_password': 'Please enter confirm Password',
      'password': 'Password',
      'login': 'Log In',
      'otp': 'Enter OTP Code',
      'number': 'Phone Number',
      'return_number': 'Please enter Number',
      'sign_in_statement': 'Enter your username and password to get started.',
      'forgot_password': 'Forgot Password?',
      'dont_have': 'Don’t have account?',
      'otp_code': 'Enter OTP Code',
      'otp_sent_to': 'OTP code has been sent to \n (+91) 6377824837.',
      'or': 'Or',
      'verify': 'Verify',
      'explore_services': 'Explore services near you',
      'earn_1000': 'Earn 1000 for every friend you refer',
      'get_a': 'Get a friend to start using Canwinn',
      'applay':'Apply Membership',
      'personal_profile':'Personal Profile',
      'gender':'Gender *',
      'dob':'Date of Birth',
      'address':'Address',
      'mobile_number':'Mobile No.',
      'marital_status':'Marital Status',
      'save':'Save',
      'Verify_Member':'Verify Member',
      'registers':'Register Yourself  To',
      'canwinn_member':'Become a CANWINN Member Today !',
      'register':'Registers',
      'active_member':'You are Now an Active\n Member!',
      'clinic_details':'Clinic Details',
      'search_hospital':'Search hospital name or speciality...',
      'filters':'Filters',
      'near_me':'Near me',
      'open':'Open 24 x 7',
      'hospital_Details':'Hospital  Details',
      'directions':'Get Direction',
      'call_Now':'Call Now',
      'senior_doctors':'Senior Doctors',
      'emergency_call':'Emergency Call 102',
      'reviews':'Reviews',
      'recent':'Recent Activity',
      'book_now':'Book Now',
      'popular_services':'Popular Services',
      'trending_offers':'Trending Offers',
      'quickAccess':'Quick Access',
      'save_canwinn_connect':'How to save with canwinn connect ?',
      'order_summar':'Order summary',
      'cart':'Your Cart',
      'add_address':'Add address and slot',
      'lab_test':'Lab Tests'
    },
    'hi_IN': {
      'google_text': 'गूगल',
      'facebook_text': 'फेसबुक',
      'sign_in': 'साइन इन करें',
      'sign_up': 'साइन अप करें',
      'enter_code': 'कृपया निम्न विवरण दर्ज करें।',
      'username': 'उपयोगकर्ता नाम',
      'email': 'ईमेल',
      'return_mail': 'कृपया ईमेल दर्ज करें',
      'return_username': 'कृपया उपयोगकर्ता नाम दर्ज करें',
      'return_password': 'कृपया पासवर्ड दर्ज करें',
      'return_confirm_password': 'कृपया पुष्टि पासवर्ड दर्ज करें',
      'password': 'पासवर्ड',
      'login': 'लॉग इन करें',
      'otp': 'ओटीपी कोड दर्ज करें',
      'number': 'फ़ोन नंबर',
      'return_number': 'कृपया नंबर दर्ज करें',
      'sign_in_statement': 'प्रारंभ करने के लिए अपना उपयोगकर्ता नाम और पासवर्ड दर्ज करें।',
      'forgot_password': 'पासवर्ड भूल गए?',
      'dont_have': 'कोई खाता नहीं है?',
      'otp_code': 'ओटीपी कोड दर्ज करें',
      'otp_sent_to': 'ओटीपी कोड भेजा गया है \n (+91) 6377824837 पर।',
      'or': 'या',
      'verify': 'सत्यापित करें',
      'explore_services': 'अपने पास की सेवाओं को खोजें',
      'earn_1000': 'हर मित्र को रेफर करने पर ₹1000 कमाएं',
      'get_a': 'मित्र को Canwinn उपयोग करने के लिए प्रेरित करें',
      'applay':'सदस्यता के लिए आवेदन करें',
      'personal_profile':'व्यक्तिगत प्रोफाइल',
      'gender':'लिंग  *',
      'dob':'जन्मतिथि',
      'address':'पता',
      'mobile_number':'मोबाइल_नंबर',
      'marital_status':'वैवाहिक स्थिति',
      'save':'जमा करें',
      'Verify_Member':'सदस्य सत्यापित करें',
      'registers':'अपने आप को पंजीकृत करें',
      'canwinn_member':'आज ही CANWINN सदस्य बनें!',
      'register':'पंजीकरण करवाना',
      'active_member':'अब आप एक सक्रिय \nसदस्य हैं!',
      'clinic_details':'क्लिनिक विवरण',
      'search_hospital':'अस्पताल का नाम या विशेषज्ञता खोजें...',
      'filters':'फिल्टर',
      'near_me':'मेरे पास',
      'open':'24 x 7 खुला',
      'hospital_Details':'अस्पताल विवरण',
      'directions':'दिशा प्राप्त करें',
      'call_Now':'Call Now',
      'senior_doctors':'वरिष्ठ डॉक्टर',
      'emergency_call':'आपातकालीन कॉल 102',
      'reviews':'समीक्षा',
      'recent':'हाल की गतिविधि',
      'book_now':'अभी बुक करें',
      'popular_services':'लोकप्रिय सेवाएँ',
      'trending_offers':'ट्रेंडिंग ऑफर',
      'quickAccess':'त्वरित पहुँच',
      'save_canwinn_connect':'कैनविन कनेक्ट के साथ कैसे बचत करें?',
      'order_summar':'आदेश सारांश',
      'cart':'आपकी गाड़ी',
      'add_address':'पता और स्लॉट जोड़ें',
      'lab_test':'प्रयोगशाला परीक्षण',
    },
  };
}
